console.log("data.js loaded");

const listingsData = [
  {
    id: 1,
    title: "Sunny Lodge",
    location: "Temp site",
    price: 120000,
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
    description: "Clean and secure rooms near Unizik campus.",
    rooms: "Self-contained",
    amenities: ["Water", "Light", "Security", "WiFi"],
    rules: "No loud music after 10pm",
    agentName: "Daniel Dominic",
    agentPhone: "08011112222"
  },
  {
    id: 2,
    title: "Green House Lodge",
    location: "Ifite-Up School",
    price: 180000,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    description: "Spacious lodge with constant water and light.",
    rooms: "Single Room",
    amenities: ["Water", "WiFi", "Security", "Parking"],
    rules: "No smoking",
    agentName: "Daniel Dominic",
    agentPhone: "08098765432"
  },
  {
    id: 3,
    title: "Dominic Lodge",
    location: "Amansea",
    price: 250000,
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    description: "Comfortable lodge with security and parking.",
    rooms: "Self-contained",
    amenities: ["Water", "Light", "Security", "WiFi", "Parking"],
    rules: "No loud parties",
    agentName: "Daniel Dominic",
    agentPhone: "08033334444"
  },
  {
    id: 4,
    title: "Sunny Hostel",
    location: "Okpuno",
    price: 115000,
    image: "https://images.unsplash.com/photo-1599929457522-9f4b9ca3e9ab",
    description: "Affordable rooms with easy transport access.",
    rooms: "Single Room",
    amenities: ["Water", "Security"],
    rules: "No loud noise",
    agentName: "Ms Stella",
    agentPhone: "08055556666"
  },
  {
    id: 5,
    title: "Haven Suites",
    location: "Aroma",
    price: 195000,
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
    description: "Modern hostel with central location.",
    rooms: "Self-contained",
    amenities: ["WiFi", "Water", "Security"],
    rules: "No smoking",
    agentName: "Mr John",
    agentPhone: "08012345678"
  },
  {
    id: 6,
    title: "Campus View Lodge",
    location: "Unizik Gate",
    price: 235000,
    image: "https://images.unsplash.com/photo-1592928304483-7d05723e61b5",
    description: "Excellent view of campus with secure perimeter.",
    rooms: "Self-contained",
    amenities: ["WiFi", "Security", "Parking"],
    rules: "No loud parties",
    agentName: "Mrs Jane",
    agentPhone: "08098765432"
  },
  {
    id: 7,
    title: "Ifite‑Down Rooms",
    location: "Ifite-Down School",
    price: 130000,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    description: "Cozy rooms perfect for students.",
    rooms: "Single Room",
    amenities: ["Water", "WiFi"],
    rules: "No loud noise",
    agentName: "Daniel Dominic",
    agentPhone: "08011112222"
  },
  {
    id: 8,
    title: "Regina Residence",
    location: "Regina",
    price: 155000,
    image: "https://images.unsplash.com/photo-1572120360610-d971b9c73d5c",
    description: "Quiet residential lodge with good utilities.",
    rooms: "Self-contained",
    amenities: ["Security", "Water"],
    rules: "No smoking",
    agentName: "Ms Stella",
    agentPhone: "08055556666"
  },
  {
    id: 9,
    title: "Okpuno Spacious",
    location: "Okpuno",
    price: 210000,
    image: "https://images.unsplash.com/photo-1560448071-59d3e46f1b47",
    description: "Spacious and serene environment.",
    rooms: "Self-contained",
    amenities: ["WiFi", "Parking", "Security"],
    rules: "No loud parties",
    agentName: "Mr John",
    agentPhone: "08012345678"
  },
  {
    id: 10,
    title: "Aroma Central Lodge",
    location: "Aroma",
    price: 175000,
    image: "https://images.unsplash.com/photo-1599909334466-139a96f77b19",
    description: "Great for students wanting city access.",
    rooms: "Single Room",
    amenities: ["Water", "WiFi", "Security"],
    rules: "Respect neighbors",
    agentName: "Mrs Jane",
    agentPhone: "08098765432"
  },
  {
    id: 11,
    title: "Temp Site Classic",
    location: "Temp site",
    price: 145000,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    description: "Classic lodge near the student hub.",
    rooms: "Self-contained",
    amenities: ["Water", "WiFi"],
    rules: "No loud noise after 11pm",
    agentName: "Daniel Dominic",
    agentPhone: "08011112222"
  },
  {
    id: 12,
    title: "Ifite Up Deluxe",
    location: "Ifite-Up School",
    price: 220000,
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
    description: "Deluxe self-contained rooms.",
    rooms: "Self-contained",
    amenities: ["Security", "Water", "WiFi", "Light"],
    rules: "No loud music late",
    agentName: "Ms Stella",
    agentPhone: "08055556666"
  },
  {
    id: 13,
    title: "Amansea Green",
    location: "Amansea",
    price: 135000,
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
    description: "Affordable lodge with greenery around.",
    rooms: "Single Room",
    amenities: ["Water", "Security"],
    rules: "No smoking",
    agentName: "Mr John",
    agentPhone: "08012345678"
  },
  {
    id: 14,
    title: "Regina Heights",
    location: "Regina",
    price: 190000,
    image: "https://images.unsplash.com/photo-1572120360610-d971b9c73d5c",
    description: "Great location near shops and transport.",
    rooms: "Self-contained",
    amenities: ["WiFi", "Security", "Parking"],
    rules: "No loud music",
    agentName: "Mrs Jane",
    agentPhone: "08098765432"
  },
  {
    id: 15,
    title: "Temp Site Suites",
    location: "Temp site",
    price: 200000,
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
    description: "Luxury suites near the Unizik student area.",
    rooms: "Self-contained",
    amenities: ["WiFi", "Security", "Parking"],
    rules: "No loud music",
    agentName: "Daniel Dominic",
    agentPhone: "08011112222"
  }
];
